include ../yw.setup.makefile
include ../cpp.setup.makefile
include ../app.setup.makefile

APP     = yw_extract
APP_SRC = $(wildcard $(YW_SRC_DIR)/yw-extract-app/*.cpp)

include ../app.targets.makefile
