
TEST_RUNNER = test_runner

SRC      = $(TESTS) $(TEST_RUNNER).cpp
INCLUDES = $(YW_INCLUDES) $(ANTLR_INCLUDES) $(GV_INCLUDES)
LIBS     = $(CPPUTEST_LIBS) $(YW_LIBS) $(CPP_LIBS) $(ANTLR_LIB) $(GV_LIBS)

test: $(TEST_RUNNER)
	./$(TEST_RUNNER) -v

runner: $(TEST_RUNNER)

$(TEST_RUNNER): $(SRC)  
	$(CXX) $(CPPFLAGS) $(CONSTANTS) $(INCLUDES) $(SRC) $(LIBS) -o $(TEST_RUNNER)

clean:
	rm -f $(TEST_RUNNER)