include ../yw.setup.makefile
include ../graphviz.setup.makefile
include ../cpp.setup.makefile
include ../tests.setup.makefile

TESTS = $(wildcard $(YW_TEST_DIR)/yw-graphviz-tests/*.cpp)

include ../test.targets.makefile
