include ../yw.setup.makefile
include ../cpp.setup.makefile
include ../tests.setup.makefile

TESTS = $(wildcard $(YW_TEST_DIR)/yw-parse-tests/*.cpp)
#TESTS = $(wildcard $(YW_TEST_DIR)/yw-parse-tests/begin_context_tests.cpp)

include ../test.targets.makefile
