include ../yw.setup.makefile
include ../graphviz.setup.makefile
include ../cpp.setup.makefile
include ../app.setup.makefile

APP     = yw-graph-app
APP_SRC = $(wildcard $(YW_SRC_DIR)/yw-graph-app/*.cpp)

include ../app.targets.makefile
