include ../yw.setup.makefile
include ../graphviz.setup.makefile
include ../cpp.setup.makefile

LIB_TARGET = libywgraphviz.a
LIB_SRC    = $(wildcard $(YW_SRC_DIR)/yw-graphviz/*.cpp)

include ../lib.targets.makefile
